name: Metrics
on:
  # Met à jour les stats tous les jours à minuit
  schedule: [{cron: "0 0 * * *"}]
  # Permet de le lancer manuellement
  workflow_dispatch:
  # Met à jour quand vous modifiez le dépôt
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Ne touchez PAS à la ligne ci-dessous, elle va lire votre secret toute seule
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Votre pseudo est configuré ici :
          user: BalkamFR
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Paris
