name: Metrics
on:
  # Met à jour tous les jours à minuit
  schedule: [{cron: "0 0 * * *"}]
  # Permet de lancer la mise à jour manuellement (bouton "Run workflow")
  workflow_dispatch:
  # Met à jour quand vous faites une modification sur le dépôt
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # C'est ici que le script va lire votre clé secrète
          # Ne touchez pas à cette ligne !
          token: ${{ secrets.Metrics-Token }}

          # Vos réglages
          user: BalkamFR  # <-- REMPLACEZ CECI par votre pseudo GitHub (sans majuscules)
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Paris
